version: "3"

dotenv:
  - .env.task

tasks:
  template:
    desc: Template for Tasks
    cmds:
      - bash {{.SCRIPT_PATH}}/{{.TASK_NAME}}.sh {{.MAIN_SCRIPT_PATH}}

  build:
    desc: Maven Build
    cmds:
      - task: template
        vars:
          TASK_NAME: build

  publish:
    desc: Publish to Maven Central
    cmds:
      - task: template
        vars:
          TASK_NAME: publish
